### PR TITLE
test fixes (added mamba for linux)

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
See title. We ran out of test budget, so it wasnt tested. Small fixes. Tests fail on linux with 137, which seems to be a memory issue...

### CODE REVIEW

**Review by simonvh — APPROVED** [review]

**Comment by Maarten-vd-Sande** [comment]
@simonvh 
mamba works on linux, but fails on osx.
conda works on osx, but fails on linux.

What makes sense to do here? Use them specifically per os?

Also, The tests run twice on Travis, I don't think there is any difference between PR and branch right? I think you should have a single webhook for both events. Might help with some of the running out of budget stuff

**Comment by simonvh** [comment]
> mamba works on linux, but fails on osx.
>conda works on osx, but fails on linux.
>
>What makes sense to do here? Use them specifically per os?

That seems a strange fix, but pragmatic so yes, let's do that. 

> Also, The tests run twice on Travis, I don't think there is any difference between PR and branch right? I think you should have > a single webhook for both events. Might help with some of the running out of budget stuff

Agree, can you fix this or is this an action that I should take?

**Comment by Maarten-vd-Sande** [comment]
I don't think I have the permissions for that. It should be under settings -> webhooks

**Comment by siebrenf** [comment]
Tests should now only run on PRs, and the develop and master branches

**Comment by Maarten-vd-Sande** [comment]
I think the problem is that we send two webhooks for a single event

**Pull request merged**
